version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - C:/Users/lemon/HTMLS/intranet-server:/usr/src/app
    environment:
      PORT: 4000
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  app-network:
    driver: bridge
